tinyMCE.addI18n('cs.media_dlg',{
title:"Vložit / upravit vložená média",
general:"Obecné",
advanced:"Pokročilé",
file:"Soubor / URL",
list:"Seznam",
size:"Rozměry",
preview:"Náhled",
constrain_proportions:"Zachovat proporce",
type:"Typ",
id:"ID",
name:"Název",
class_name:"Třída",
vspace:"Svislý odstup",
hspace:"Vodorovný odstup",
play:"Autoplay",
loop:"Loop",
menu:"Zobrazit nabídku",
quality:"Kvalita",
scale:"Scale",
align:"Zarovnání",
salign:"SAlign",
wmode:"Průhlednost",
bgcolor:"Pozadí",
base:"Base",
flashvars:"Flashvars",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"Cache",
hidden:"Hidden",
controller:"Controller",
kioskmode:"Kiosk mode",
playeveryframe:"Play every frame",
targetcache:"Target cache",
correction:"No correction",
enablejavascript:"Enable Javascript",
starttime:"Start time",
endtime:"End time",
href:"Href",
qtsrcchokespeed:"Choke speed",
target:"Target",
volume:"Volume",
autostart:"Auto start",
enabled:"Enabled",
fullscreen:"Fullscreen",
invokeurls:"Invoke URLs",
mute:"Mute",
stretchtofit:"Stretch to fit",
windowlessvideo:"Windowless video",
balance:"Balance",
baseurl:"Base URL",
captioningid:"Captioning id",
currentmarker:"Current marker",
currentposition:"Current position",
defaultframe:"Default frame",
playcount:"Play count",
rate:"Rate",
uimode:"UI Mode",
flash_options:"Flash",
qt_options:"Quicktime",
wmp_options:"Windows media player",
rmp_options:"Real media player",
shockwave_options:"Shockwave",
autogotourl:"Auto goto URL",
center:"Center",
imagestatus:"Image status",
maintainaspect:"Maintain aspect",
nojava:"No java",
prefetch:"Prefetch",
shuffle:"Shuffle",
console:"Console",
numloop:"Num loops",
controls:"Controls",
scriptcallbacks:"Script callbacks",
swstretchstyle:"Stretch style",
swstretchhalign:"Stretch H-Align",
swstretchvalign:"Stretch V-Align",
sound:"Sound",
progress:"Progress",
qtsrc:"QT Src",
qt_stream_warn:"Streamed rtsp resources should be added to the QT Src field under the advanced tab.\nYou should also add a non streamed version to the Src field..",
align_top:"Nahoru",
align_right:"Vpravo",
align_bottom:"Dolů",
align_left:"Vlevo",
align_center:"Na střed",
align_top_left:"Vlevo nahoře",
align_top_right:"Vpravo nahoře",
align_bottom_left:"Vlevo dole",
align_bottom_right:"Vpravo dole",
flv_options:"Flash video",
flv_scalemode:"Scale mode",
flv_buffer:"Buffer",
flv_startimage:"Start image",
flv_starttime:"Start time",
flv_defaultvolume:"Default volumne",
flv_hiddengui:"Hidden GUI",
flv_autostart:"Auto start",
flv_loop:"Loop",
flv_showscalemodes:"Show scale modes",
flv_smoothvideo:"Smooth video",
flv_jscallback:"JS Callback"
});
