tinyMCE.addI18n('cs.advlink_dlg',{
title:"Vložit / Upravit odkaz",
url:"URL odkazu",
target:"Cíl",
titlefield:"Titulek",
is_email:"Zadaná URL se zdá být e-mailovou adresou, chcete vložit potřebnou předponu mailto:?",
is_external:"Zadaná URL se zdá být externím odkazem, chcete vložit potřebnou předponu http://?",
list:"Odkazy",
general_tab:"Hlavní",
popup_tab:"Vyskakovací okno",
events_tab:"Události",
advanced_tab:"Pokročilé",
general_props:"Obecné vlastnosti",
popup_props:"Vlastnosti vyskakovacího okna",
event_props:"Události",
advanced_props:"Pokročilé vlastnosti",
popup_opts:"Možnosti",
anchor_names:"Kotvy",
target_same:"Otevřít ve stejném okně / rámci",
target_parent:"Otevřít v nadřazeném okně / rámci",
target_top:"Otevřít v nejvyšším rámci (nahradí všechny rámce)",
target_blank:"Otevřít v novém okně",
popup:"Javascriptové vyskakovací okno",
popup_url:"URL vyskakovacího okna",
popup_name:"Název okna",
popup_return:"Vložit 'return false'",
popup_scrollbars:"Zobrazit posuvníky",
popup_statusbar:"Zobrazit stavový řádek",
popup_toolbar:"Zobrazit panel nástrojů",
popup_menubar:"Zobrazit panel nabídek",
popup_location:"Zobrazit panel adresy",
popup_resizable:"Umožnot změnu velikosti okna",
popup_dependent:"Závislost (pouze Mozilla/Firefox)",
popup_size:"Velikost",
popup_position:"Pozice (X/Y)",
id:"ID",
style:"Styl",
classes:"Třídy",
target_name:"Název cíle",
langdir:"Směr textu",
target_langcode:"Jazyk cíle",
langcode:"Kód jazyku",
encoding:"Kódování znaků cíle",
mime:"MIME typ cíle",
rel:"Vztah stránky k cíli",
rev:"Vztah cíle ke stránce",
tabindex:"Tabindex",
accesskey:"Accesskey",
ltr:"Zleva doprava",
rtl:"Zprava doleva",
link_list:"Odkazy"
});
