tinyMCE.addI18n('cs.table_dlg',{
general_tab:"Obecná",
advanced_tab:"Pokročilá",
general_props:"Obecná nastavení",
advanced_props:"Pokročilá nastavení",
rowtype:"Řádky v části tabulky",
title:"Vložit / Upravit tabulku",
width:"Šířka (px)",
height:"Výška (px)",
cols:"Sloupců",
rows:"Řádků",
cellspacing:"Vnější okraj (px)",
cellpadding:"Vnitřní okraj (px)",
border:"Rámeček (px)",
align:"Zarovnání",
align_default:"Výchozí",
align_left:"doleva",
align_right:"doprava",
align_middle:"na střed",
row_title:"Vlastnosti řádků",
cell_title:"Vlastnosti buněk",
cell_type:"Typ",
valign:"Svislé zarovnání",
align_top:"nahoru",
align_bottom:"dolů",
bordercolor:"Barva rámečku",
bgcolor:"Barva pozadí",
merge_cells_title:"Sloučit buňky",
id:"ID",
style:"Styl",
langdir:"Směr psaní textu",
langcode:"Kód jazyka",
mime:"Typ MIME cíle",
ltr:"zleva doprava",
rtl:"zprava doleva",
bgimage:"Obrázek pozadí",
summary:"Obsah tabulky",
td:"Buňka",
th:"Hlavička",
cell_cell:"Aktualizovat vybranou buňku",
cell_row:"Aktualizovat všechny buňky v řádku",
cell_all:"Aktualizovat všechny buňky v tabulce",
row_row:"Aktualizovat vybraný řádek",
row_odd:"Aktualizovat vybraný řádek",
row_even:"Aktualizovat stejné řádky v tabulce",
row_all:"Aktualizovat všechny řádky v tabulce",
thead:"Záhlaví tabulky",
tbody:"Tělo tabulky",
tfoot:"Zápatí tabulky",
scope:"Oblast",
rowgroup:"Skupina řádků",
colgroup:"Skupina sloupců",
col_limit:"Máte překročen maximální počet sloupců v {$cols}.",
row_limit:"Máte překročen maximální počet řádků v {$rows}.",
cell_limit:"Máte překročen maximální počet buněk v {$cells}.",
missing_scope:"Skutečně chcete pokračovat bez určení rozsahu v buňce záhlaví tabulky. Bez tohoto mohou být obsah tabulky a vložená data pro některé handicapované uživatele nesrozumitelná.",
caption:"Titulek tabulky",
frame:"Vykreslení rámečku",
frame_none:"nebude zobrazen (void)",
frame_groups:"pouze mezi oddíly (groups)",
frame_rows:"pouze mezi řádky (rows)",
frame_cols:"pouze mezi sloupci (cols)",
frame_all:"kompletní mžížka (all)",
rules:"Vykreslení mřížky",
rules_void:"nebude zobrazen (void)",
rules_above:"pouze horní strana (above)",
rules_below:"pouze spodní strana (below)",
rules_hsides:"pouze horní a spodní strana (hsides)",
rules_lhs:"pouze levá strana (lhs)",
rules_rhs:"pouze pravá strana (rhs)",
rules_vsides:"pouze pravá a levá strana (vsides)",
rules_box:"všechny čtyři strany (box)",
rules_border:"všechny čtyři strany (border)"
});
