tinyMCE.addI18n('cs.advanced',{
style_select:"Styly",
font_size:"Velikost písma",
fontdefault:"Písmo",
block:"Formát",
paragraph:"Odstavec",
div:"Blok",
address:"Adresa",
pre:"předformátovaný text",
h1:"Nadpis 1",
h2:"Nadpis 2",
h3:"Nadpis 3",
h4:"Nadpis 4",
h5:"Nadpis 5",
h6:"Nadpis 6",
blockquote:"Citace",
code:"Kód",
samp:"Ukázka kódu",
dt:"Deklarace termínu ",
dd:"Definice termínu",
bold_desc:"Tučné (Ctrl+B)",
italic_desc:"Kurzíva (Ctrl+I)",
underline_desc:"Podtrhnout (Ctrl+U)",
striketrough_desc:"Přeškrtnout",
justifyleft_desc:"Zarovnat vlevo",
justifycenter_desc:"Zarovnat na střed",
justifyright_desc:"Zarovnat vpravo",
justifyfull_desc:"Zarovnat do bloku",
bullist_desc:"Neuspořádaný seznam",
numlist_desc:"Uspořádaný seznam",
outdent_desc:"Zmenšit odsazení",
indent_desc:"Zvětšit odsazení",
undo_desc:"Zpět (Ctrl+Z)",
redo_desc:"Znovu (Ctrl+Y)",
link_desc:"Vložit / Upravit odkaz",
unlink_desc:"Zrušit odkaz",
image_desc:"Vložit / Upravit obrázek",
cleanup_desc:"Vyčistit kód",
code_desc:"Zdrojový kód HTML",
sub_desc:"Dolní index",
sup_desc:"Horní index",
hr_desc:"Vložit vodorovnou čáru",
removeformat_desc:"Odstranit formátování",
custom1_desc:"Uživatelský popis",
forecolor_desc:"Vybrat barvu textu",
backcolor_desc:"Vybrat barvu pozadí",
charmap_desc:"Vložit symbol",
visualaid_desc:"Přepnout pokyny / neviditelné prvky",
anchor_desc:"Vložit / Upravit kotvu",
cut_desc:"Vyjmout",
copy_desc:"Kopírovat",
paste_desc:"Vložit",
image_props_desc:"Vlastnosti obrázku",
newdocument_desc:"Nový dokument",
help_desc:"Nápověda",
blockquote_desc:"Citace",
clipboard_msg:"Volby Kopírovat / Vyjmout / Vložit nejsou v  Mozilla a Firefox dostupné.\nPotřebujete o tomto problému více informací?",
path:"Cesta",
newdocument:"Skutečně chcete vymazat celý obsah?",
toolbar_focus:"Přejít na panel nástrojů - Alt+Q, Přejít do editoru - Alt-Z, Přejít na cestu prvku - Alt-X",
more_colors:"Další barvy"
});
