tinyMCE.addI18n('cs.advanced_dlg',{
about_title:"O TinyMCE",
about_general:"O TinyMCE",
about_help:"Nápověda",
about_license:"Licence",
about_plugins:"Pluginy",
about_plugin:"Plugin",
about_author:"Autor",
about_version:"Verze",
about_loaded:"Nahrané pluginy",
anchor_title:"Vložit / Upravit kotvu",
anchor_name:"Název kotvy",
code_title:"Editor zdrojového HTML",
code_wordwrap:"Zalomit řádky",
colorpicker_title:"Vybrat barvu",
colorpicker_picker_tab:"Nabrat barvu",
colorpicker_picker_title:"Nabrat barvu",
colorpicker_palette_tab:"Barevná paleta",
colorpicker_palette_title:"Barevná paleta",
colorpicker_named_tab:"Pojmenované barvy",
colorpicker_named_title:"Pojmenované barvy",
colorpicker_color:"Barva:",
colorpicker_name:"Název:",
charmap_title:"Vložit symbol",
image_title:"Vložit / Upravit obrázek",
image_src:"URL obrázku",
image_alt:"Popis obrázku",
image_list:"Obrázky",
image_border:"Ohraničení",
image_dimensions:"Rozměry",
image_vspace:"Svislý odstup",
image_hspace:"Vodorovný odstup",
image_align:"Zarovnání",
image_align_baseline:"na účaří",
image_align_top:"k horní hraně",
image_align_middle:"účaří řádku na střed",
image_align_bottom:"k dolní hraně",
image_align_texttop:"s nejvyšším bodem textu",
image_align_textbottom:"na nejnižší úroveň řádku",
image_align_left:"k levému okraji",
image_align_right:"k pravému okraji",
link_title:"Vloži/upravit odkaz",
link_url:"URL odkazu",
link_target:"Cíl",
link_target_same:"Otevřít odkaz ve stejném okně",
link_target_blank:"Otevřít odkaz v novém okně",
link_titlefield:"Titulek",
link_is_email:"Zadaná URL se zdá být e-mailovou adresou, chcete vložit potřebnou předponu mailto:?",
link_is_external:"Zadaná URL se zdá být externím odkazem, chcete vložit potřebnou předponu http://?",
link_list:"Odkazy"
});
