tinyMCE.addI18n('cs.fullpage_dlg',{
title:"Vlastnosti dokumentu",
meta_tab:"Obecné",
appearance_tab:"Vzhled",
advanced_tab:"Pokročilé",
meta_props:"Meta informace",
langprops:"Jazyk a kódování",
meta_title:"Title",
meta_keywords:"Keywords",
meta_description:"Description",
meta_robots:"Robots",
doctypes:"Doctype",
langcode:"Kód jazyku",
langdir:"Směr psaní textu",
ltr:"zleva doprava",
rtl:"zprava doleva",
xml_pi:"XML deklarace",
encoding:"Kódování znaků",
appearance_bgprops:"Vlastnosti pozadí",
appearance_marginprops:"Vnější okraje těla",
appearance_linkprops:"Barva odkazů",
appearance_textprops:"Vlastnosti textu",
bgcolor:"Barva pozadí",
bgimage:"Obrázek na pozadí",
left_margin:"Levý vnější odstup",
right_margin:"Pravý vnější odstup",
top_margin:"Horní vnější odstup",
bottom_margin:"Dolní vnější odstup",
text_color:"Barva textu",
font_size:"Velikost písma",
font_face:"Typ písma",
link_color:"Barva odkazu",
hover_color:"Barva hover odkazu",
visited_color:"Barva navštíveného odkazu",
active_color:"Barva aktivního odkazu",
textcolor:"Barva",
fontsize:"Velikost písma",
fontface:"Typ písma",
meta_index_follow:"Index a follow pro odkazy",
meta_index_nofollow:"Index a nofollow pro odkazy",
meta_noindex_follow:"Noindex, ale follow pro odkazy",
meta_noindex_nofollow:"Noindex a nofollow pro odkazy",
appearance_style:"Vlastnosti stylu",
stylesheet:"Styl",
style:"Styl",
author:"Autor",
copyright:"Autorská práva",
add:"Přidat nový element",
remove:"Odstranit vybraný element",
moveup:"Přemístit vybraný element nahoru",
movedown:"Přemístit vybraný element dolů",
head_elements:"Hlavní elementy",
info:"Informace",
add_title:"Element Title",
add_meta:"Element Meta",
add_script:"Element Script",
add_style:"Element Styl",
add_link:"Element odkaz",
add_base:"Element Base",
add_comment:"Komentář",
title_element:"Element Title",
script_element:"Element Script",
style_element:"Element Styl",
base_element:"Element Base",
link_element:"Element odkaz",
meta_element:"Element Meta",
comment_element:"Komentář",
src:"Src",
language:"Jazyk",
href:"Href",
target:"Cíl",
type:"Typ",
charset:"Znaková sada",
defer:"Defer",
media:"Media",
properties:"Vlastnosti",
name:"Název",
value:"Hodnota",
content:"Obsah",
rel:"Rel",
rev:"Rev",
hreflang:"Href lang",
general_props:"Obecné",
advanced_props:"Pokročilé"
});
