tinyMCE.addI18n('cs.xhtmlxtras_dlg',{
attribute_label_title:"Název",
attribute_label_id:"ID",
attribute_label_class:"Třída",
attribute_label_style:"Styl",
attribute_label_cite:"Citace",
attribute_label_datetime:"Datum/Čas",
attribute_label_langdir:"Směr psaní textu",
attribute_option_ltr:"Zleva doprava",
attribute_option_rtl:"Zprava doleva",
attribute_label_langcode:"Kód jazyka",
attribute_label_tabindex:"Pozice elementu (tabindex)",
attribute_label_accesskey:"Klávesová zkratka",
attribute_events_tab:"Události",
attribute_attrib_tab:"Vlastnosti",
general_tab:"Základní nastavení",
attrib_tab:"Vlastnosti",
events_tab:"Události",
fieldset_general_tab:"Základní nastavení",
fieldset_attrib_tab:"Vlastnosti elementu",
fieldset_events_tab:"Události elementu",
title_ins_element:"Přidaný text",
title_del_element:"Smazaný text",
title_acronym_element:"Ustálený výraz",
title_abbr_element:"Zkratka",
title_cite_element:"Citace",
remove:"Odstranit",
insert_date:"Vložit aktuální datum / čas",
option_ltr:"zleva doprava",
option_rtl:"zprava doleva",
attribs_title:"Vložit / Upravit vlastnosti"
});
