tinyMCE.addI18n('cs.style_dlg',{
title:"Upravit styly CSS",
apply : "Uložit",
text_tab : "Písmo",
background_tab : "Pozadí",
block_tab : "Text",
box_tab : "Prvek",
border_tab : "Ohraničení",
list_tab : "Seznam",
positioning_tab : "Poloha",
text_props : "Text",
text_font : "Písmo",
text_size : "Velikost písma",
text_weight : "Váha písma",
text_style : "Styl písma",
text_variant : "Varianta písma",
text_lineheight : "Výška řádku",
text_case : "Transformace písma",
text_color : "Barva písma",
text_decoration : "Dekorace písma",
text_overline : "nadtržený text",
text_underline : "podtržený text",
text_striketrough : "přeškrtnutý text",
text_blink : "blikající text",
text_none : "normální text",
background_color : "Barva pozadí",
background_image : "Obrázek na pozadí",
background_repeat : "Opakování obrázku",
background_attachment : "Posun obrázku",
background_hpos : "Poloha horizontálně",
background_vpos : "Poloha vertikálně",
block_wordspacing : "Mezery mezi slovy",
block_letterspacing : "Mezery mezi písmeny",
block_vertical_alignment : "Vertikální zarovnání textu",
block_text_align : "Horizontální zarovnání textu",
block_text_indent : "Velikost odsazení prvního řádku",
block_whitespace : "Způsob zacházení s mezerami",
block_display : "Způsob zobrazení",
box_width : "Šířka",
box_height : "Výška",
box_float : "Plovoucí",
box_clear : "Obtékání",
padding : "Vnitřní okraj",
same : "Všechny strany",
top : "Nahoře",
right : "Vpravo",
bottom : "Dole",
left : "Vlevo",
margin : "Vnější okraj",
style : "Styl",
width : "Šířka",
height : "Výška",
color : "Barva",
list_type : "Typ",
bullet_image : "Ikona odrážky",
position : "Umístění",
positioning_type : "Typ",
visibility : "Zobrazení",
zindex : "Z-index",
overflow : "Přetékání",
placement : "Odstup",
clip : "Odstřižení"
});
