tinyMCE.addI18n('cs.advimage_dlg',{
tab_general:"Obecné",
tab_appearance:"Vzhled",
tab_advanced:"Pokročilé",
general:"Obecné",
title:"Titulek",
preview:"Náhled",
constrain_proportions:"Zachovat proporce",
langdir:"Směr textu",
langcode:"Kód jazyka",
long_desc:"Dlouhý popis odkazu",
style:"Styl",
classes:"Třída",
ltr:"Zleva doprava",
rtl:"Zprava doleva",
id:"ID",
map:"Obrázková mapa",
swap_image:"Výměna obrázku",
alt_image:"Alternativní obrázek",
mouseover:"pro mouseover",
mouseout:"pro mouseout",
misc:"Různé",
example_img:"Vzhled náhledu obrázku",
missing_alt:"Skutečně chcete pokračovat bez zadání popisu obrázku? Bez zadání popisu nemusí být obrázek dostupný uživatelům se zdravotním omezením, nebo těm, kdo používají textový prohlížeč či těm, kdo mají vypnuté zobrazování obrázků.",
dialog_title:"Vložit / Upravit obrázek",
src:"URL obrázku",
alt:"Popis obrázku",
list:"Obrázky",
border:"Ohraničení",
dimensions:"Rozměry",
vspace:"Svislý odstup",
hspace:"Vodorovný odstup",
align:"Zarovnání",
align_baseline:"na účaří",
align_top:"k horní hraně",
align_middle:"účaří řádku na střed",
align_bottom:"k dolní hraně",
align_texttop:"s nejvyšším bodem textu",
align_textbottom:"na nejnižší úroveň řádku",
align_left:"k levému okraji",
align_right:"k pravému okraj",
image_list:"Seznam obrázků"
});
